version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    allow:
      - update-types:
          - version-update:semver-patch
          - version-update:semver-minor
  - package-ecosystem: docker
    directory: /orchestrator
    schedule:
      interval: weekly
    allow:
      - update-types:
          - version-update:semver-patch
          - version-update:semver-minor
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    allow:
      - update-types:
          - version-update:semver-patch
          - version-update:semver-minor
